name: Playwright Tests

on:
  push:
    branches:
      - main  # Run tests when pushing to main
  pull_request:
    branches:
      - main  # Run tests on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Gets your code

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Use your preferred Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright & Browsers
        run: |
          python -m playwright install --with-deps  # Installs Chromium, Firefox, WebKit

      - name: Run Playwright Tests
        run: pytest --headed --slowmo 500  # Adjust options as needed